### ISSUE TITLE
Large error when compiling.

### ISSUE THREAD

**Issue by drakea** [westbaer/irecovery#1]
When I type in make linux, it gives me this error report. What do I do to stop this?

"gcc irecovery.c -o irecovery -lusb -lreadline
irecovery.c:22:17: error: usb.h: No such file or directory
irecovery.c:23:31: error: readline/readline.h: No such file or directory
irecovery.c: In function ‘irecv_init’:
irecovery.c:48: warning: assignment makes pointer from integer without a cast
irecovery.c:48: error: dereferencing pointer to incomplete type
irecovery.c:49: error: dereferencing pointer to incomplete type
irecovery.c:49: error: dereferencing pointer to incomplete type
irecovery.c:50: error: dereferencing pointer to incomplete type
irecovery.c:50: error: dereferencing pointer to incomplete type
irecovery.c:51: warning: assignment makes pointer from integer without a cast
irecovery.c: In function ‘irecv_console’:
irecovery.c:236: warning: assignment makes pointer from integer without a cast
irecovery.c:253: warning: format ‘%s’ expects type ‘char _’, but argument 2 has type ‘int’
irecovery.c: In function ‘irecv_sendcmd’:
irecovery.c:280: warning: format ‘%s’ expects type ‘char *’, but argument 2 has type ‘int’
irecovery.c: In function ‘main’:
irecovery.c:323: error: ‘SIGINT’ undeclared (first use in this function)
irecovery.c:323: error: (Each undeclared identifier is reported only once
irecovery.c:323: error: for each function it appears in.)
make: *_\* [linux] Error 1"

**Comment by johankj** [comment]
Try one of the updated forks, like GreySyntax's, iH8Sn0w or P0sixninjas :)
